### ISSUE TITLE
Home page carousel in header

### ISSUE THREAD

**Issue by sean-rad-dude** [lokioatmeal/dev-dukes#1]

**Comment by lokioatmeal** [comment]
You can see this home hero carousel at the URL below. For future reference, the preview_theme_id in the URL should point to a specific unpublished theme and should display the change request in question. After you click it, you should see a message at the bottom of the screen that says, “You are currently previewing the theme: [name_of_theme]” If you do not see that message then something is likely wrong.

![shopify-preview-message](https://cloud.githubusercontent.com/assets/2258300/19668435/b414e8d8-9a0c-11e6-8962-a2ae09826b4c.jpg)

[dev-dukes.myshopify.com/?preview_theme_id=152400902](url)

Questions / comments:

1. I see no previous or next arrows in the comp so there aren’t any in this.
2. I see no slide indicators (AKA dots) in the comp so there aren’t any in this.
3. I find the fade transition to be favorable to a slide so that is how I set this up.
4. From a UX POV, I find it very strange that the Goodbye Jerky slide is the only one with a full-width background image and a footer bar. The other three slides all feel more consistent.
5. Are these supposed to link to anything?
6. Regarding that last question, the Single-Serve Packs slide has what appears to be one of those weird buttons in the comp and there are at least two problems with that; 1. to what would it link? 2. those weird buttons do not work well at all when place over patterned backgrounds. See (and zoom into) the button in the Smoked in Detroit section on the home for example. That button on Smoked in Detroit requires yet more CSS and still doesn’t look quite right.

**Comment by sean-rad-dude** [comment]
Dude, this link is no working. Can you resend?

**Comment by lokioatmeal** [comment]
Very Interdasting. Try replacing dev-dukes.my… with dukesmeats.com.

[dukesmeats.com/?preview_theme_id=152400902](http://dukesmeats.com/?preview_theme_id=152400902)

**Comment by sean-rad-dude** [comment]
This looks cool
can you please add arrows and circle things ?

Can you start with current header on live site.

1. Real whole ingredients (current homepage) / link to ingredient page page

2. Lordy lordy. / Link to shorty product overview page

3. shortcuts suck / link to process page

4. Protein pickle ups / link to shorty hatch chili product

5. goodbye jerky  / link to beef steak strips products page



We are working on more full screen images that match jerky one, we just don't have them yet.


Cool ?

**Comment by lokioatmeal** [comment]
Please review at the test URL provided previously. I have update the slide order, added arrows, and slide indicator dots.

Note, the zigzag background pattern will change when I change it for that other outstanding request since they all use the same asset.
